### ISSUE TITLE
Example throwing errors

### ISSUE THREAD

**Issue by shalomabitan** [FocusSchoolSoftware/pg-live-query#9]
Hi,

Super excited for what you've built here. Thing is I was running the simple example and got this error and am not sure why. May you please help me?

Steps (in case you were wondering)
1. npm init
2. installed and saved yours and npm pg.
3. copy + pasted example
4. edited it for pg pool config
5. ran it - failed

```
$ node app.js
/Users/shalomabitan/sites/testing/node-pg-live-query/node_modules/pg-live-query/index.js:4

class LiveQuery extends Watcher {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/shalomabitan/sites/testing/node-pg-live-query/app.js:3:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

npm version 3.10.9
node verison v5.3.0

Thanks for any help :)

**Comment by shalomabitan** [comment]
Hi,

This has been solved. I needed to be using node version >= 6.x
